add setup of SPI and I2C to run during post install script

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,14 +1,51 @@
 #!/bin/sh
 
-#set -e
+set -e
 
-#echo "IM HERE"
+case "$1" in
 
-#mkdir ~/rstem
-#mkdir ~/rstem/cellapps
-#cp -r ./cellapps ~/rstem
-#mkdir ~/rstem/projects
-#cp -r ./projects ~/rstem
+  configure)
+    # Set up SPI, I2C, etc...
+    
+    # lines to be in /etc/modules:
+    declare -a modules=('i2c-bcm2708' 'i2c-dev' 'spidev' 'snd-bcm2835');
+    for mod in ${modules[@]}; do
+		if grep -q $mod /etc/modules; then
+			echo "$mod already in /etc/modules."
+		else
+			echo "$mod not found in /etc/modules, adding...."
+			echo $mod | sudo tee -a /etc/modules >> /dev/null
+		fi
+	done
+	
+	# lines to be commented out in /etc/modprobe.d/raspi-blacklist.conf:
+    declare -a blacklist=('i2c-bcm2708' 'spi-bcm2708');
+    for mod in ${blacklist[@]}; do
+		if grep -q "^blacklist $mod" /etc/modprobe.d/raspi-blacklist.conf; then
+			echo "$mod is blacklisted, commenting out...."
+			sudo sed -i -e "s/blacklist $mod/#blacklist $mod/g" /etc/modprobe.d/raspi-blacklist.conf 
+		else
+			echo "$mod is not blacklisted."
+		fi
+	done
+  ;;
 
+  abort-upgrade|abort-remove|abort-deconfigure)
+    exit 0
+  ;;
 
-# TODO: detect running on raspberry pi then set up SPI, etc...
+  *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
+  ;;
+
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+db_stop
+
+exit 0
